---

owner: cust000

family: 'internal_id'
family_name: '643594'
samples:
  - analysis_type: wes
    sample_id: ADM1059A2
    capture_kit: Agilent_SureSelectCRE.V1
    father: ADM1059A1
    mother: ADM1059A3
    sample_name: NA12882
    phenotype: affected
    sex: male
    expected_coverage: 30
    mt_bam: scout/demo/reduced_mt.bam
    vcf2cytosure: scout/demo/ADM1059A2.dummy.cgh
    tissue_type: blood

  - analysis_type: wes
    sample_id: ADM1059A1
    capture_kit: Agilent_SureSelectCRE.V1
    father: '0'
    mother: '0'
    sample_name: NA12877
    phenotype: unaffected
    sex: male
    expected_coverage: 30
    mt_bam: scout/demo/reduced_mt.bam
    vcf2cytosure: scout/demo/ADM1059A1.dummy.cgh
    tissue_type: blood

  - analysis_type: wes
    sample_id: ADM1059A3
    capture_kit: Agilent_SureSelectCRE.V1
    father: '0'
    mother: '0'
    sample_name: NA12878
    phenotype: unaffected
    sex: female
    expected_coverage: 30
    mt_bam: scout/demo/reduced_mt.bam
    vcf2cytosure: scout/demo/ADM1059A3.dummy.cgh
    tissue_type: blood

vcf_snv: scout/demo/643594.clinical.vcf.gz
vcf_sv: scout/demo/643594.clinical.SV.vcf.gz
vcf_str: scout/demo/643594.clinical.str.annotated.vcf.gz
vcf_snv_research: scout/demo/643594.research.vcf.gz
vcf_sv_research: scout/demo/643594.research.SV.vcf.gz

madeline: scout/demo/madeline.xml

peddy_ped: scout/demo/643594.peddy.ped
peddy_ped_check: scout/demo/643594.ped_check.csv
peddy_sex_check: scout/demo/643594.sex_check.csv

delivery_report: scout/demo/delivery_report.html

default_gene_panels: [panel1]
gene_panels: [panel1]
chromograph_image_files: scout/demo/images
chromograph_prefixes:
    'roh': "roh_chr"
    'upd': "upd_chr"
    'chr': "cytoband.txt.chr"
smn_tsv: scout/demo/643594.solo.smn.tsv

# meta data
rank_model_version: '1.20'
sv_rank_model_version: '1.5'
rank_score_threshold: -100
analysis_date: 2016-10-12 14:00:46
human_genome_build: 37
