---

owner: cust000

family: 'internal_id'
family_name: '643594'
lims_id: 'LID1234'
synopsis:
  - 'Test case consisting of an affected male individual'
  - 'Both parents are unaffected'
phenotype_terms:
  - HP:0001298
  - HP:0001250
cohorts:
  - pedhep
  - mito
samples:
  - analysis_type: wes
    sample_id: ADM1059A2
    capture_kit: Agilent_SureSelectCRE.V1
    father: ADM1059A1
    mother: ADM1059A3
    sample_name: NA12882
    phenotype: affected
    sex: male
    expected_coverage: 30
    tissue_type: blood
    mt_bam: scout/demo/reduced_mt.bam
    vcf2cytosure: scout/demo/ADM1059A2.test.cgh
    rna_coverage_bigwig: scout/demo/ACC5963A1_lanes_1234_star_sorted_sj_filtered.bigWig
    splice_junctions_bed: scout/demo/ACC5963A1_lanes_1234_star_sorted_sj_filtered_sorted.bed.gz

    chromograph_images:
        'autozygous': 'scout/demo/images/chromograph_demo/autozygous_regions'
        'coverage': 'scout/demo/images/chromograph_demo/coverage'
        'upd_regions': 'scout/demo/images/chromograph_demo/upd_regions'
        'upd_sites': 'scout/demo/images/chromograph_demo/upd_sites'

  - analysis_type: wes
    sample_id: ADM1059A1
    capture_kit: Agilent_SureSelectCRE.V1
    father: '0'
    mother: '0'
    sample_name: NA12877
    phenotype: unaffected
    sex: male
    expected_coverage: 30
    tissue_type: blood
    mt_bam: scout/demo/reduced_mt.bam
    vcf2cytosure: scout/demo/ADM1059A1.test.cgh

  - analysis_type: wes
    sample_id: ADM1059A3
    capture_kit: Agilent_SureSelectCRE.V1
    father: '0'
    mother: '0'
    sample_name: NA12878
    phenotype: unaffected
    sex: female
    expected_coverage: 30
    tissue_type: blood
    mt_bam: scout/demo/reduced_mt.bam
    vcf2cytosure: scout/demo/ADM1059A3.test.cgh

custom_images:
  section_one:
    - title: A png image
      description: A very good description
      width: 500
      height: 100
      path: scout/demo/images/custom_images/640x480_one.png
    - title: A jpg image
      description: A very good description
      width: 500
      path: scout/demo/images/custom_images/640x480_two.jpg
  section_two:
    - title: A SVG image
      description: Another very good description
      path: scout/demo/images/custom_images/640x480_three.svg

vcf_snv: scout/demo/643594.clinical.vcf.gz
vcf_sv: scout/demo/643594.clinical.SV.vcf.gz
vcf_str: scout/demo/643594.clinical.str.stranger.vcf.gz
vcf_snv_research: scout/demo/643594.research.vcf.gz
vcf_sv_research: scout/demo/643594.research.SV.vcf.gz

smn_tsv: scout/demo/643594.solo.smn.tsv

madeline: scout/demo/madeline.xml

peddy_ped: scout/demo/643594.peddy.ped
peddy_check: scout/demo/643594.ped_check.csv
peddy_sex: scout/demo/643594.sex_check.csv

delivery_report: scout/demo/delivery_report.html
gene_fusion_report: scout/demo/draw-fusions-example.pdf

default_gene_panels: [panel1]
gene_panels: [panel1]

# meta data
rank_model_version: '1.20'
sv_rank_model_version: '1.5'
rank_score_threshold: -100
analysis_date: 2016-10-12 14:00:46
human_genome_build: 37
