---

owner: cust000

family: 'internal_id_2'
family_name: '643595'
samples:
  - analysis_type: wes
    sample_id: ACC17113A6
    capture_kit: Agilent_SureSelectCRE.V1
    father:
    mother:
    sample_name: NA12882
    phenotype: affected
    sex: male
    expected_coverage: 30
    mt_bam: scout/demo/reduced_mt.bam
    vcf2cytosure: scout/demo/ADM1059A2.test.cgh
    tissue_type: blood
    rna_coverage_bigwig: scout/demo/ACC5963A1_lanes_1234_star_sorted_sj_filtered.bigWig
    splice_junctions_bed: scout/demo/ACC5963A1_lanes_1234_star_sorted_sj_filtered_sorted.bed.gz

vcf_snv: /Users/chiararasi/Documents/work/scout_real_case/legiblemarlin/contentnewt-sample-ACC17113A6.vcf

madeline: scout/demo/madeline.xml

peddy_ped: scout/demo/643594.peddy.ped
peddy_ped_check: scout/demo/643594.ped_check.csv
peddy_sex_check: scout/demo/643594.sex_check.csv

delivery_report: scout/demo/delivery_report.html

default_gene_panels: [panel1]
gene_panels: [panel1]

# meta data
rank_model_version: '1.20'
rank_score_threshold: 5
analysis_date: 2016-10-12 14:00:46
human_genome_build: '37'
