---

owner: cust000

family: 'cancer_test'
family_name: 'cancer_case'
samples:
  - analysis_type: panel
    sample_id: 999-99
    tumor_type: Chordoma
    capture_kit: Twist.V1
    sample_name: 999-99
    phenotype: affected
    sex: male
    expected_coverage: 90
    mt_bam: scout/demo/reduced_mt.bam
    tmb: 7
    msi: 15
    tumor_purity: 1

  - analysis_type: panel
    sample_id: 998-99
    capture_kit: Twist.V1
    sample_name: 998-99
    phenotype: unaffected
    sex: male
    expected_coverage: 90
    mt_bam: scout/demo/reduced_mt.bam

vcf_cancer: scout/demo/cancer_test.vcf.gz
vcf_cancer_sv: scout/demo/manta_vep_94_annotated_sv_cancer_file.vcf.gz

#vcf_snv: scout/demo/cancer_test.vcf.gz
#vcf_sv: scout/demo/manta_vep_94_annotated_sv_cancer_file.vcf.gz

#vcf_snv_research: scout/demo/cancer_test.vcf.gz
#vcf_sv_research: scout/demo/manta_vep_94_annotated_sv_cancer_file.vcf.gz

#vcf_cancer_research: scout/demo/manta_vep_94_annotated_sv_cancer_file.vcf.gz
#vcf_cancer_sv_research: scout/demo/manta_vep_94_annotated_sv_cancer_file.vcf.gz

delivery_report: scout/demo/delivery_report.html
cnv_report: scout/demo/cancer_cnv_report.pdf
coverage_qc_report: scout/demo/cancer_coverage_qc_report.html


# meta data
rank_model_version: '1.1'
rank_score_threshold: -100
analysis_date: 2018-10-12 14:00:46
human_genome_build: 37
track: cancer
